## This is a basic workflow to help you get started with Actions

name: CI

## Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  server_name: GANGAVALI\SQLEXPRESS
  database: partsunlimited
  db_user: akshay
  PACKAGE_TEMP_PATH: Content\D_C\a\PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Nuget Restore
      run: nuget restore
      
    - name: Buils the Project
      run: |
        msbuild PartsUnlimited.sln /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir" 
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@2.1.0
      with:  
        name: PartsUnlimited
        path: ${{github.workspace}}\stagingdir
  
  Database:
    runs-on: db
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2    
    - name: Restore the database
      run: |
         & 'C:\Program Files\sqlpackage-win7-x64-en-US-15.0.4826.1\sqlpackage.exe' /Action:Publish /SourceFile:${{github.workspace}}\pul.dacpac /tsn:${{env.server_name}} /tdn:${{env.database}} /su:${{env.db_user}} /sp:${{ secrets.db_password }}

  deploy:
    name: DEPLOY TO AZURE WEB APP
    runs-on: windows-latest
    needs: [build]
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: PartsUnlimited
        path: ${{github.workspace}}
    - name: Extract Artifact
      run: expand-archive -path '*.zip' -destinationpath '.\webapp'
      shell: pwsh
    - name: Azure WebApp Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: partsproject
        publish-profile: ${{secrets.publish_profile}}
        package: webapp\${{env.PACKAGE_TEMP_PATH}}


